# Generated by Django 6.1 on 2026-08-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ej: 2 Guantes/Packs', max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Precio en $', max_digits=6)),
                ('subtitle', models.CharField(default='Pet Glove Wipes', max_length=150)),
                ('badge', models.CharField(blank=True, help_text='Ej: Más Popular', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
